
configfile: "config.yaml"


rule:
    input:
        "test.out"
    output:
        txt="test.out2"
    params:
        xy=True
    script:
        "scripts/test.sh"

rule:
    input:
        "test.in"
    output:
        txt="test.out"
    params:
        xy=True
    script:
        "scripts/test.R"

rule:
    output:
        "test.in"
    script:
        "scripts/test.py"

